---
# Every test file has one or more tests...
test_name: Create a geocube and run bulk homogenization using Grenadier dataset

# ...and each test has one or more stages (e.g. an HTTP request)
marks:
  - usefixtures:
      - clean_resources_from_db
  - geocube
  - homogenization
includes:
  - !include common.yaml

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: create client
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/clients"
      method: POST
      json:
        companyName: "test company name"

    # ...and the expected response code and body
    response:
      status_code: 200
      save:
        body:
          client_uuid: client.uuid


  - name: create project
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/projects"
      method: POST
      json:
        project:
          basin: "midland"
          name: "test project"
          crs: "EPSG:32038"
          unit: "FEET"
          clientUuid: "{client_uuid:s}"

    # ...and the expected response code and body
    response:
      status_code: 200
      save:
        body:
          project_uuid: project.uuid


  - name: create geocube
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/stage"
      method: POST
      json:
        name: "test cube"
        projectUuid: "{project_uuid:s}"

    response:
      status_code: 200
      save:
        body:
          cube_uuid: uuid

  - name: add wells
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/wells"
      method: POST
      json: !include data/grenadier/homogenization/header-wells.yaml

    response:
      status_code: 200
      save:
        $ext:
          function: utilities.utils:get_well_uid_mapping

  - name: add data (well logs)
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/wells/{BET THE FARM UNIT_1:s}/data"
      method: POST
      files:
        file: "data/grenadier/homogenization/well_logs/BET_THE_FARM_UNIT1_1_WDVG_Petrophysic_sp_rock_properties.csv"
        type: 'RPE'
    response:
      status_code: 200


  - name: add data (well logs)
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/wells/{BUCHANAN 42 1:s}/data"
      method: POST
      files:
        file: "data/grenadier/homogenization/well_logs/BUCHANAN_42_WDVG_Petrophysic_sp_rock_properties.csv"
        type: 'RPE'
    response:
      status_code: 200

  - name: add input data (grid connection)
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/inputs"
      method: POST
      files:
        file: "data/grenadier/homogenization/Grenadier_Zone_DF_connnectivity_15ft.csv"
        type: 'GRIDCONNECTION'
    response:
      status_code: 200

  - name: add input data  (pore pressure)
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/inputs"
      method: POST
      files:
        file: "data/grenadier/homogenization/calibrated_pore_pressure_model.csv"
        type: 'POREPRESSURE'
    response:
      status_code: 200

  - name: edit homogenization settings
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/homogenization"
      method: PUT
      json: !include data/grenadier/homogenization/homogenizationsettings.yaml
    response:
      status_code: 200

  - name: run homogenization
    # Define the request to be made...
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}/homogenization/start"
      method: POST
      json:
        wells:
          - BET THE FARM UNIT_1
          - BUCHANAN 42 1
    response:
      status_code: 200

  - name: verify successfull homogenization run
    # Define the request to be made...
    delay_before: 30
    request:
      url: "{toolkit-qa.host:s}/runs/geocube/{cube_uuid:s}"
      method: GET
    response:
      status_code: 200
      body:
        $ext:
          function: utilities.utils:assert_finish_status_homogenization
---
